# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4fdb19aef475a08d14f799151c001e52b7f5ada63f088af2c1f479423a1a24439aa9312c9e474e82ccbe7fb927b1621993a0b1d6c3ce232f9400b773de36627a

test:
  secret_key_base: ae7cb0aebfc5fd14cebefddc7be0a305b7626ae63b7612c1fb424c95b38467064f869606092cfdc42445cf505ebcac4a7057196ed6bb4663c04c94d0a4fc522b
  
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 1082b2497fe8ed00272885f0c8dc8740e4784419ce040c38c390e0c314155ca7e52485b1bb4cdef9becbd19236dfb5a186951a22bc6be94c5d2435478336f218